src/EthernaIndex/Areas/Admin/Pages/VideoManifests/Index.cshtml.cs
//   Copyright 2021-present Etherna Sagl
// 
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using Etherna.EthernaIndex.Domain;
using Etherna.EthernaIndex.Domain.Models.VideoAgg;
using Etherna.MongoDB.Driver.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Etherna.EthernaIndex.Areas.Admin.Pages.VideoManifests
{
    public class IndexModel : PageModel
    {
        // Models.
        public class VideoManifestDto
        {
            public VideoManifestDto(
                string manifestHash,
                string title)
            {
                if (manifestHash is null)
                    throw new ArgumentNullException(nameof(manifestHash));
                if (title is null)
                    throw new ArgumentNullException(nameof(title));

                ManifestHash = manifestHash;
                Title = title;
            }

            public string ManifestHash { get; }
            public string Title { get; }
        }

        // Consts.
        private const int PageSize = 20;

        // Fields.
        private readonly IIndexDbContext indexDbContext;

        // Constructor.
        public IndexModel(
            IIndexDbContext indexDbContext)
        {
            this.indexDbContext = indexDbContext;
            ErrorMessage = "";
        }

        // Properties.
        public int CurrentPage { get; private set; }
        public string ErrorMessage { get; private set; }
        public long MaxPage { get; private set; }
        public IEnumerable<VideoManifestDto> VideoManifests { get; set; } = default!;

        // Methods.
        public async Task<IActionResult> OnGetAsync(
            string? manifestHash,
            int? p)
        {
            CurrentPage = p ?? 0;
            if (!string.IsNullOrWhiteSpace(manifestHash))
            {
                var videoManifests = await indexDbContext.VideoManifests.TryFindOneAsync(v => v.Manifest.Hash == manifestHash);

                if (videoManifests is not null)
                    return RedirectToPage("Manifest", new { manifestHash });

                VideoManifests = Array.Empty<VideoManifestDto>();
                ErrorMessage = "ManifestHash not found.";
            }
            else
            {
                var paginatedVideoManifests = await indexDbContext.VideoManifests.QueryPaginatedElementsAsync(
                    vm => vm,
                    vm => vm.Id,
                    CurrentPage,
                    PageSize);

                MaxPage = paginatedVideoManifests.MaxPage;

                VideoManifests = paginatedVideoManifests.Elements.Select(
                    e => new VideoManifestDto(
                        e.Manifest.Hash,
                    e.TryGetTitle() ?? ""));
            }

            return new PageResult();
        }
    }
}

src/EthernaIndex/Areas/Admin/Pages/VideoManifests/Manage.cshtml.cs
//   Copyright 2021-present Etherna Sagl
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using Etherna.Authentication.Extensions;
using Etherna.EthernaIndex.Domain;
using Etherna.EthernaIndex.Domain.Models;
using Etherna.EthernaIndex.Services.Domain;
using Etherna.EthernaIndex.Services.Tasks;
using Etherna.MongoDB.Driver.Linq;
using Hangfire;
using Hangfire.States;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Etherna.EthernaIndex.Areas.Admin.Pages.VideoManifests
{
    public class ManageModel : PageModel
    {
        public class VideoManifestDto
        {
            public VideoManifestDto(
                VideoManifest videoManifest,
                bool hasOtherValidManifest)
            {
                if (videoManifest == null)
                    throw new ArgumentNullException(nameof(videoManifest));

                Id = videoManifest.Id;
                ReviewApproved = videoManifest.ReviewApproved;
                CreationDateTime = videoManifest.CreationDateTime;
                Description = videoManifest.Description;
                Duration = videoManifest.Duration;
                ErrorsDetails = videoManifest.ErrorValidationResults.Select(i => $"[{i.ErrorNumber}]: {i.ErrorMessage}");
                IsValid = videoManifest.IsValid;
                ManifestHash = videoManifest.ManifestHash.Hash;
                OriginalQuality = videoManifest.OriginalQuality;
                OwnerAddress = videoManifest.Id;
                Title = videoManifest.Id;
                VideoInfo = new VideoInfoDto(videoManifest.Video.Id, hasOtherValidManifest);
                ValidationTime = videoManifest.ValidationTime;

                Sources = videoManifest.Sources != null ?
                    videoManifest.Sources.Select(i => new MetadataVideoSourceDto(
                        i.Bitrate,
                        i.Reference,
                        i.Size,
                        i.Quality)) : new List<MetadataVideoSourceDto>();
                Thumbnail = videoManifest.Thumbnail != null ? new SwarmImageRawDto
                    (
                        videoManifest.Thumbnail.AspectRatio,
                        videoManifest.Thumbnail.BlurHash,
                        videoManifest.Thumbnail.Sources.ToDictionary(i => i.Key, i => i.Value)
                    ) : null;
            }

            // Properties.
            public string Id { get; set; } = default!;
            public bool? ReviewApproved { get; set; }
            public DateTime CreationDateTime { get; set; }
            public string? Description { get; set; } = default!;
            public float? Duration { get; set; }
            public IEnumerable<string> ErrorsDetails { get; set; } = default!;
            public bool? IsValid { get; set; }
            public string ManifestHash { get; set; } = default!;
            public string? OriginalQuality { get; set; }
            public string OwnerAddress { get; set; } = default!;
            public IEnumerable<MetadataVideoSourceDto> Sources { get; set; }
            public SwarmImageRawDto? Thumbnail { get; set; }
            public string? Title { get; set; } = default!;
            public VideoInfoDto VideoInfo { get; set; }
            public DateTime? ValidationTime { get; set; }

            // Methods.
            public class MetadataVideoSourceDto
            {
                public MetadataVideoSourceDto(
                    int? bitrate,
                    string reference,
                    int? size,
                    string quality)
                {
                    Bitrate = bitrate;
                    Reference = reference;
                    Size = size;
                    Quality = quality;
                }

                public int? Bitrate { get; set; }
                public string Reference { get; set; } = default!;
                public int? Size { get; set; }
                public string Quality { get; set; } = default!;
            }

            public class SwarmImageRawDto
            {
                public SwarmImageRawDto(
                    float aspectRatio,
                    string blurhash,
                    IReadOnlyDictionary<string, string> sources)
                {
                    AspectRatio = aspectRatio;
                    Blurhash = blurhash;
                    Sources = sources;
                }

                public float AspectRatio { get; set; }
                public string Blurhash { get; set; } = default!;
                public IReadOnlyDictionary<string, string> Sources { get; set; } = default!;
            }

            public class VideoInfoDto
            {
                public VideoInfoDto(
                    string videoId, 
                    bool hasOtherValidManifest)
                {
                    VideoId = videoId;
                    HasOtherValidManifest = hasOtherValidManifest;
                }

                public string VideoId { get; set; }
                public bool HasOtherValidManifest { get; set; }
            }
        }

        // Fields.
        private readonly IBackgroundJobClient backgroundJobClient;
        private readonly IIndexDbContext indexDbContext;
        private readonly IUserService userService;
        private readonly IVideoReportService videoReportService;

        // Constructor.
        public ManageModel(
            IBackgroundJobClient backgroundJobClient,
            IIndexDbContext indexDbContext,
            IUserService userService,
            IVideoReportService videoReportService)
        {
            if (indexDbContext is null)
                throw new ArgumentNullException(nameof(indexDbContext));

            this.backgroundJobClient = backgroundJobClient;
            this.indexDbContext = indexDbContext;
            this.userService = userService;
            this.videoReportService = videoReportService;
        }

        // Properties.
        public VideoManifestDto VideoManifest { get; private set; } = default!;

        // Methods.
        public async Task OnGetAsync(string manifestHash)
        {
            await InitializeAsync(manifestHash);
        }

        public async Task<IActionResult> OnPostApprovedManifest(
            string videoId,
            string manifestHash)
        {
            await SetReviewAsync(videoId, manifestHash, ContentReviewStatus.ApprovedManifest);

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostRejectManifest(
            string videoId,
            string manifestHash)
        {
            await SetReviewAsync(videoId, manifestHash, ContentReviewStatus.RejectManifest);

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostRejectVideo(
            string videoId,
            string manifestHash)
        {
            await SetReviewAsync(videoId, manifestHash, ContentReviewStatus.RejectVideo);

            return RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostForceNewValidationAsync(string manifestHash)
        {
            var videoManifest = await indexDbContext.VideoManifests.FindOneAsync(c => c.ManifestHash.Hash == manifestHash);
            backgroundJobClient.Create<MetadataVideoValidatorTask>(
                    task => task.RunAsync(videoManifest.Video.Id, videoManifest.ManifestHash.Hash),
                    new EnqueuedState(Queues.METADATA_VIDEO_VALIDATOR));

            return RedirectToPage("Index");
        }

        // Helpers.
        private async Task InitializeAsync(string manifestHash)
        {
            // Video info
            var videoManifest = await indexDbContext.VideoManifests.FindOneAsync(vm => vm.ManifestHash.Hash == manifestHash);
            var video = await indexDbContext.Videos.FindOneAsync(v => v.Id == videoManifest.Video.Id);

            var hasOtherValidManifest = video.VideoManifests.Any(vm => vm.IsValid == true &&
                                                                        vm.ManifestHash.Hash != videoManifest.ManifestHash.Hash);

            VideoManifest = new VideoManifestDto(
                videoManifest, 
                hasOtherValidManifest);
        }

        private async Task SetReviewAsync(string videoId, string manifestHash, ContentReviewStatus contentReviewStatus)
        {
            var address = HttpContext!.User.GetEtherAddress();
            var (user, _) = await userService.FindUserAsync(address);

            await videoReportService.SetReviewAsync(videoId, manifestHash, contentReviewStatus, user, "");
        }

    }
}

src/EthernaIndex/Areas/Admin/Pages/VideoManifests/Index.cshtml
@*   Copyright 2021-present Etherna Sagl
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *@

@page
@model Etherna.EthernaIndex.Areas.Admin.Pages.VideoManifests.IndexModel
@{
    ViewData["Title"] = "Video Manifests";

    var pageSelectorModel = new PageSelectorModel(Model.CurrentPage, (int)Model.MaxPage);
}

<div class="row">
    <div class="col-12 mb-3 text-center mt-1">
        <h2>@ViewData["Title"]</h2>
    </div>
</div>

<form method="get"
      asp-route-p="@Model.CurrentPage">

    <div class="form-row">
        <div class="col-4 mb-3">
            <input id="ManifestHash" name="ManifestHash" type="text" placeholder="manifest hash" class="form-control" />
        </div>
    </div>

    <div class="form-row">
        <div class="col-12 mb-3">
            <input type="submit" class="btn btn-primary" value="Find" />
        </div>
    </div>

    <div class="form-row">
        <div class="col-4 mb-3">
            <span>@Model.ErrorMessage</span>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th></th>
                        <th>Manifest Hash</th>
                        <th>Title</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var videoReport in Model.VideoManifests)
                    {
                    <tr>
                        <td class="align-middle">
                            <a class="btn btn-primary" asp-page="Manifest" asp-route-manifestHash="@videoReport.ManifestHash">Manage</a>
                        </td>
                        <td class="align-middle">@videoReport.ManifestHash</td>
                        <td class="align-middle">@videoReport.Title</td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <partial name="_PageSelector" model="pageSelectorModel" />
    </div>
</div>

src/EthernaIndex/Areas/Admin/Pages/VideoManifests/Manage.cshtml
@*  *   Copyright 2021-present Etherna Sagl
    *
    *   Licensed under the Apache License, Version 2.0 (the "License");
    *   you may not use this file except in compliance with the License.
    *   You may obtain a copy of the License at
    *
    *       http://www.apache.org/licenses/LICENSE-2.0
    *
    *   Unless required by applicable law or agreed to in writing, software
    *   distributed under the License is distributed on an "AS IS" BASIS,
    *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    *   See the License for the specific language governing permissions and
    *   limitations under the License.
*@

@page
@model Etherna.EthernaIndex.Areas.Admin.Pages.VideoManifests.ManageModel

<form id="client-form" Method="post">
    <input type="hidden" asp-for="VideoManifest.ManifestHash" />

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h2>@Model.VideoManifest.Title</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Description:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.Description
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Creation:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.CreationDateTime
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>ManifestHash:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.ManifestHash
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Validation Time:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            @Model.VideoManifest.ValidationTime
        </div>
        <div class="col-1 mb-3 text-left mt-1">
            <strong>IsValid:</strong>
        </div>
        <div class="col-1 mb-3 text-left mt-1">
            @Model.VideoManifest.IsValid
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Errors:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            <ul>
                @foreach (var errorsDetail in Model.VideoManifest.ErrorsDetails)
                {
                    <li>@errorsDetail</li>
                }
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>ContentApproved:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            @(Model.VideoManifest.ReviewApproved?.ToString() ?? "Not Defined")
        </div>
    </div>

    <div class="form-row">
        <div class="col-12 mb-3">
            <input type="submit" asp-page-handler="ApprovedManifest" class="btn btn-primary" value="Approve Manifest" name="button" />
            @if (Model.VideoManifest.VideoInfo.HasOtherValidManifest)
            {
                <input type="submit" asp-page-handler="RejectManifest" class="btn btn-primary" value="Reject Manifest" name="button" />
            }
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h5>Video Info</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Video Id:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            @Model.VideoManifest.VideoInfo.VideoId
        </div>
    </div>

    <div class="form-row">
        <div class="col-12 mb-3">
            <input type="submit" asp-page-handler="RejectVideo" class="btn btn-primary" value="Reject Video" name="button" />
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h5>Validation Actions</h5>
        </div>
    </div>

    <div class="form-row">
        <div class="col-12 text-center  mb-3">
            <input type="submit" asp-page-handler="ForceNewValidation" class="btn btn-primary" value="Force New Validation" name="button" />
        </div>
    </div>

</form>

src/EthernaIndex/Areas/Admin/Pages/VideoManifests/Manifest.cshtml
@*   Copyright 2021-present Etherna Sagl
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 *@

@page
@model Etherna.EthernaIndex.Areas.Admin.Pages.VideoManifests.ManifestModel

<form id="client-form" Method="post">
    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h2>@Model.VideoManifest.Title</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Description:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.Description
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Creation:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.CreationDateTime
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>ManifestHash:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoManifest.ManifestHash
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Validation Time:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            @Model.VideoManifest.ValidationTime
        </div>
        <div class="col-1 mb-3 text-left mt-1">
            <strong>IsValid:</strong>
        </div>
        <div class="col-1 mb-3 text-left mt-1">
            @Model.VideoManifest.IsValid
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Errors:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            <ul>
                @foreach (var errorsDetail in Model.VideoManifest.ErrorsDetails)
                {
                    <li>@errorsDetail</li>
                }
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h5>Video Info</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Video Id:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            @Model.VideoManifest.VideoInfo?.VideoId
        </div>
    </div>

    <div class="row">
        <div class="col-12 mb-3 text-center mt-1">
            <h5>Validation Actions</h5>
        </div>
    </div>

    <div class="form-row">
        <div class="col-12 text-center  mb-3">
            <input type="submit"
                   asp-page-handler="ForceNewValidation"
                   asp-route-manifestHash="@Model.VideoManifest.ManifestHash"
                   class="btn btn-primary" value="Force New Validation" name="button" />
        </div>
    </div>

</form>