src/EthernaIndex/Areas/Admin/Pages/VideoModeration/Video.cshtml.cs
//   Copyright 2021-present Etherna Sagl
// 
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Etherna.Authentication;
using Etherna.EthernaIndex.Domain;
using Etherna.EthernaIndex.Domain.Models;
using Etherna.EthernaIndex.Domain.Models.VideoAgg;
using Etherna.EthernaIndex.Services.Domain;
using Etherna.MongoDB.Driver;
using Etherna.MongoDB.Driver.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Etherna.EthernaIndex.Areas.Admin.Pages.VideoModeration
{
    public class VideoModel : PageModel
    {
        // Models.
        public abstract class HistoryElementBase
        {
            // Properties.
            public string Id { get; protected set; } = default!;
            public string AuthorSharedInfoId { get; protected set; } = default!;
            public string Description { get; protected set; } = default!;
            public DateTime CreationDateTime { get; protected set; }
        }
        
        public class InputModel
        {
            [Display(Name = "Reason")]
            public string Reason { get; set; } = default!;
        }
        
        public class ReportHistoryElement : HistoryElementBase
        {
            // Constructor.
            public ReportHistoryElement(UnsuitableVideoReport report)
            {
                if (report == null) throw new ArgumentNullException(nameof(report));

                Id = report.Id;
                AuthorSharedInfoId = report.ReporterAuthor.SharedInfoId;
                CreationDateTime = report.CreationDateTime;
                Description = report.Description;
            }
        }
        
        public class ReviewHistoryElement : HistoryElementBase
        {
            // Constructors.
            public ReviewHistoryElement(ManualVideoReview review)
            {
                if (review == null) throw new ArgumentNullException(nameof(review));

                Id = review.Id;
                AuthorSharedInfoId = review.Author.SharedInfoId;
                CreationDateTime = review.CreationDateTime;
                Description = review.Description;
                IsValid = review.IsValidResult;
            }

            // Properties.
            public bool IsValid { get; }
        }

        // Fields.
        private readonly IEthernaOpenIdConnectClient ethernaOidcClient;
        private readonly IIndexDbContext indexDbContext;
        private readonly IUserService userService;

        // Constructor.
        public VideoModel(
            IEthernaOpenIdConnectClient ethernaOidcClient,
            IIndexDbContext indexDbContext,
            IUserService userService)
        {
            this.ethernaOidcClient = ethernaOidcClient;
            this.indexDbContext = indexDbContext;
            this.userService = userService;
        }

        // Properties.
        [BindProperty]
        public InputModel Input { get; set; } = default!;
        public DateTime CreationDateTime { get; private set; }
        public IEnumerable<HistoryElementBase> HistoryElements { get; private set; } = default!;
        public bool IsFrozen { get; private set; }
        public VideoManifest? LastValidManifest { get; private set; }
        public string VideoId { get; private set; } = default!;

        // Methods.
        public async Task OnGetAsync(
            string id)
        {
            VideoId = id;

            // Get video info
            var video = await indexDbContext.Videos.FindOneAsync(v => v.Id == id);
            CreationDateTime = video.CreationDateTime;
            IsFrozen = video.IsFrozen;
            LastValidManifest = video.LastValidManifest;

            // Get history.
            var unsuitableVideoReports = await indexDbContext.UnsuitableVideoReports.QueryElementsAsync(
                elements => elements.Where(r => r.Video.Id == id)
                    .ToListAsync());

            var manualVideoReviews = await indexDbContext.ManualVideoReviews.QueryElementsAsync(
                elements => elements.Where(r => r.Video.Id == id)
                    .ToListAsync());

            HistoryElements = unsuitableVideoReports.Select(r => new ReportHistoryElement(r))
                .Union<HistoryElementBase>(manualVideoReviews.Select(r => new ReviewHistoryElement(r)))
                .OrderByDescending(historyElement => historyElement.CreationDateTime);
        }

        public async Task<IActionResult> OnPostApproveVideo(
            string id)
        {
            if (!ModelState.IsValid)
                return RedirectToPage(new { id });

            await CreateReviewAsync(id, true, Input.Reason);
            return RedirectToPage(new { id });
        }

        public async Task<IActionResult> OnPostRejectVideo(
            string id)
        {
            if (!ModelState.IsValid)
                return RedirectToPage(new { id });

            await CreateReviewAsync(id, false, Input.Reason);
            return RedirectToPage(new { id });
        }

        // Helpers.
        private async Task CreateReviewAsync(string videoId, bool isValid, string reason)
        {
            var address = await ethernaOidcClient.GetEtherAddressAsync();
            var (user, _) = await userService.FindUserAsync(address);
            var video = await indexDbContext.Videos.FindOneAsync(videoId);

            // Create ManualReview.
            await indexDbContext.ManualVideoReviews.CreateAsync(new ManualVideoReview(user, reason, isValid, video));
        }
    }
}

src/EthernaIndex/Areas/Api/Controllers/VideosController.cs
//   Copyright 2021-present Etherna Sagl
// 
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
// 
//       http://www.apache.org/licenses/LICENSE-2.0
// 
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

using Etherna.EthernaIndex.Areas.Api.DtoModels;
using Etherna.EthernaIndex.Areas.Api.InputModels;
using Etherna.EthernaIndex.Areas.Api.Services;
using Etherna.EthernaIndex.Attributes;
using Etherna.EthernaIndex.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace Etherna.EthernaIndex.Areas.Api.Controllers
{
    [ApiController]
    [ApiVersion("0.3")]
    [Route("api/v{api-version:apiVersion}/[controller]")]
    public class VideosController : ControllerBase
    {
        // Fields.
        private readonly IVideosControllerService service;

        // Constructors.
        public VideosController(IVideosControllerService controllerService)
        {
            this.service = controllerService;
        }

        // Get.

        /// <summary>
        /// Get video info by id.
        /// </summary>
        /// <param name="id">The video id</param>
        [HttpGet("{id}")]
        [Obsolete("Use \"find2\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<VideoDto> FindByIdAsync_old(
            [Required] string id) =>
            service.FindByIdAsync_old(id);

        /// <summary>
        /// Get video info by id.
        /// </summary>
        /// <param name="id">The video id</param>
        [HttpGet("{id}/find2")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<Video2Dto> FindByIdAsync(
            [Required] string id) =>
            service.FindByIdAsync(id);

        /// <summary>
        /// Get paginated video comments by id
        /// </summary>
        /// <param name="id">Video id</param>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("{id}/comments")]
        [Obsolete("Use \"{id}/comments3\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IEnumerable<CommentDto>> GetVideoCommentsAsync(
            [Required] string id,
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            (await service.GetVideoCommentsAsync_old(id, page, take)).Elements;

        /// <summary>
        /// Get paginated video comments by id
        /// </summary>
        /// <param name="id">Video id</param>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("{id}/comments2")]
        [Obsolete("Use \"{id}/comments3\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<PaginatedEnumerableDto<CommentDto>> GetVideoComments2Async(
            [Required] string id,
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            service.GetVideoCommentsAsync_old(id, page, take);
        
        /// <summary>
        /// Get paginated video comments by id
        /// </summary>
        /// <param name="id">Video id</param>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("{id}/comments3")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<PaginatedEnumerableDto<Comment2Dto>> GetVideoComments3Async(
            [Required] string id,
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            service.GetVideoCommentsAsync(id, page, take);

        /// <summary>
        /// Get validation info by id.
        /// </summary>
        /// <param name="id">The video id</param>
        [HttpGet("{id}/validations")]
        [Obsolete("Use \"{id}/validation2\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IEnumerable<VideoManifestStatusDto>> ValidationsStatusByIdAsync_old(
            [Required] string id) =>
            (await service.GetValidationStatusByIdAsync_old(id)).ManifestsStatus;

        /// <summary>
        /// Get validation info by id.
        /// </summary>
        /// <param name="id">The video id</param>
        [HttpGet("{id}/validation")]
        [Obsolete("Use \"{id}/validation2\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<VideoStatusDto> ValidationsStatusByIdAsync_old2(
            [Required] string id) =>
            service.GetValidationStatusByIdAsync_old(id);

        /// <summary>
        /// Get validation info by id.
        /// </summary>
        /// <param name="id">The video id</param>
        [HttpGet("{id}/validation2")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<IEnumerable<VideoManifestStatusDto>> ValidationsStatusByIdAsync(
            [Required] string id) =>
            service.GetValidationStatusByIdAsync(id);

        /// <summary>
        /// Get list of last uploaded videos.
        /// </summary>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("latest")]
        [Obsolete("Use \"latest3\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public async Task<IEnumerable<VideoDto>> GetLastUploadedVideosAsync_old0(
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            (await service.GetLastUploadedVideosAsync_old(page, take)).Elements;

        /// <summary>
        /// Get list of last uploaded videos.
        /// </summary>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("latest2")]
        [Obsolete("Use \"latest3\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public Task<PaginatedEnumerableDto<VideoDto>> GetLastUploadedVideosAsync_old1(
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            service.GetLastUploadedVideosAsync_old(page, take);

        /// <summary>
        /// Get list of last uploaded videos.
        /// </summary>
        /// <param name="page">Current page of results</param>
        /// <param name="take">Number of items to retrieve. Max 100</param>
        /// <response code="200">Current page on list</response>
        [HttpGet("latest3")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        public Task<PaginatedEnumerableDto<VideoPreviewDto>> GetLastUploadedVideosAsync(
            [Range(0, int.MaxValue)] int page,
            [Range(1, 100)] int take = 25) =>
            service.GetLastUploadedVideosAsync(page, take);

        /// <summary>
        /// Get video info by manifest hash.
        /// </summary>
        /// <param name="hash">The video hash</param>
        [HttpGet("manifest/{hash}")]
        [Obsolete("Use \"manifest2\" instead")]
        [SimpleExceptionFilter]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public Task<VideoDto> FindByManifestHashAsync_old(
            [Required] string hash) =>
            service.FindByManifestHashAsync_old(hash);

src/EthernaIndex/Areas/Admin/Pages/Videos/Index.cshtml
@page
@using static Etherna.EthernaIndex.Areas.Admin.Pages.Videos.IndexModel;
@model Etherna.EthernaIndex.Areas.Admin.Pages.Videos.IndexModel
@{
    ViewData["Title"] = Model.VideoModelSelected.Manifest?.Title ?? "";

    var pageSelectorModel = new PageSelectorModel(Model.CurrentPage, (int)Model.MaxPage, routeData: Model.CustomRouteData);
}

<div class="row">
    <div class="col-12 mb-3 text-center mt-1">
        <h5>Video Info</h5>
    </div>
</div>

<div class="row">
    <div class="col-2 mb-3 text-left mt-1">
        <strong>Video Id:</strong>
    </div>
    <div class="col-2 mb-3 text-left mt-1">
        @Model.VideoModelSelected.VideoId
    </div>
</div>

<div class="row">
    <div class="col-2 mb-3 text-left mt-1">
        <strong>Video Creation:</strong>
    </div>
    <div class="col-2 mb-3 text-left mt-1">
        @Model.VideoModelSelected.CreationDateTime
    </div>
</div>

@if (Model.VideoModelSelected.Manifest is not null)
{
    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Title:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoModelSelected.Manifest.Title
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Description:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoModelSelected.Manifest.Description
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Manifest Creation:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoModelSelected.Manifest.CreationDateTime
        </div>
    </div>

    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>ManifestHash:</strong>
        </div>
        <div class="col-10 mb-3 text-left mt-1">
            @Model.VideoModelSelected.Manifest.ManifestHash
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-2 mb-3 text-left mt-1">
            <strong>Video Manifest:</strong>
        </div>
        <div class="col-2 mb-3 text-left mt-1">
            Missing valid manifest
        </div>
    </div>
}

<div class="row">
    <div class="col-12 mb-3 text-center mt-1">
        <h5>Reports</h5>
    </div>
</div>


<form id="client-form" Method="post">
    <div class="form-row">
        <div class="col-12 mb-3">
            <input type="hidden" asp-for="VideoModelSelected.VideoId" name="VideoId" />
            <input type="submit" asp-page-handler="ApproveVideo" class="btn btn-primary" value="Approve Video" name="button" />
            <input type="submit" asp-page-handler="RejectVideo" class="btn btn-primary" value="Reject Video" name="button" />
            <input asp-for="Input.Reason" type="text" placeholder="Reason" class="form-control" />
        </div>
    </div>
</form>

<div class="row">
    <div class="col-12">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>History</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var report in Model.VideoModelSelected.Reports)
                    {
                        <tr>
                            @if (@report.DetailType == VideoReportModel.UnsuitableReportDetailType.ReportVideo)
                            {
                                <td class="align-middle">@report.Date <b>User:</b> @report.Address <b>Reported:</b> @report.Description</td>
                            }
                            else
                            {
                                <td class="align-middle">@report.Date <b>User</b> @report.Address <b>Review:</b> @(report.IsValid ? "Accepted" : "Rejected") <b>Motivation:</b> @report.Description</td>
                            }
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <partial name="_PageSelector" model="pageSelectorModel" asp-route-videoId="@Model.VideoModelSelected.VideoId" />
    </div>
</div>